name: Continuous integration and deployment
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  Lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install -d
        pipenv install -d > /dev/null 2>&1
        
    - name: Lint with flake8
      run: |
        pipenv run python rfc5242handlelogging.py

  deploy_heroku:
    runs-on: ubuntu-18.04
    needs: Lint
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v1
    - name: login
      uses: actions/heroku@1.0.0
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:login
    - name: push
      uses: actions/heroku@1.0.0
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
      with:
        args: container:push -a $HEROKU_APP web
    - name: release
      uses: actions/heroku@1.0.0
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
      with:
        args: container:release -a $HEROKU_APP web
